import type { Metadata } from 'next'
import './globals.css'
import { relative } from 'path'
import { Footer, Navbar } from '@/components'


export const metadata: Metadata = {
  title: 'Car Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
